// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//
// Code generated by Microsoft (R) Rust Code Generator.

#![cfg_attr(docsrs, feature(doc_cfg))]

mod generated;
pub use generated::*;
pub mod internal_operation;
pub mod public_operation;
pub mod relative_model_in_operation;
pub mod shared_model_in_operation;
