// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//
// Code generated by Microsoft (R) Rust Code Generator.

#![cfg_attr(docsrs, feature(doc_cfg))]

mod generated;
pub use generated::*;
pub mod internal_operation;
pub mod public_operation;
pub mod relative_model_in_operation;
pub mod shared_model_in_operation;

// Exercise pub(crate) client methods so dead_code warnings stay enabled
// for real issues. These methods are internal-access and have no callers
// in a test crate, but would be called by a public convenience layer in
// a real SDK.
#[allow(dead_code)]
const _: () = {
    fn _touch_internal_operation() {
        let client = AccessClient::with_no_credential("https://example.com", None).unwrap();
        let sub = client.get_access_internal_operation_client();
        drop(sub.internal_decorator_in_internal("x", None));
        drop(sub.no_decorator_in_internal("x", None));
        drop(sub.public_decorator_in_internal("x", None));
    }

    fn _touch_relative_model_in_operation() {
        let client = AccessClient::with_no_credential("https://example.com", None).unwrap();
        let sub = client.get_access_relative_model_in_operation_client();
        drop(sub.discriminator("x", None));
        drop(sub.operation("x", None));
    }

    fn _touch_shared_model_in_operation() {
        let client = AccessClient::with_no_credential("https://example.com", None).unwrap();
        let sub = client.get_access_shared_model_in_operation_client();
        drop(sub.internal("x", None));
    }
};
