// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.

// this should be preserved and is not next to the begin delimiter.

// BEGIN GENERATED CODE -- do not edit from here till END
mod generated;

pub mod clients {
    pub use crate::generated::clients::{KeyVaultClient, KeyVaultClientOptions};
}

pub mod models {
    pub use crate::generated::clients::method_options::{
        KeyVaultClientBackupSecretOptions, KeyVaultClientDeleteSecretOptions,
        KeyVaultClientGetDeletedSecretOptions, KeyVaultClientGetSecretOptions,
        KeyVaultClientListDeletedSecretsOptions, KeyVaultClientListSecretVersionsOptions,
        KeyVaultClientListSecretsOptions, KeyVaultClientPurgeDeletedSecretOptions,
        KeyVaultClientRecoverDeletedSecretOptions, KeyVaultClientRestoreSecretOptions,
        KeyVaultClientSetSecretOptions, KeyVaultClientUpdateSecretOptions,
    };
    pub use crate::generated::enums::*;
    pub use crate::generated::models::*;
}

pub use crate::generated::clients::{KeyVaultClient, KeyVaultClientOptions};
// END GENERATED CODE

// this should also be preserved and is not next to the end delimiter.
