/*---------------------------------------------------------------------------------------------
*  Copyright (c) Microsoft Corporation. All rights reserved.
*  Licensed under the MIT License. See License.txt in the project root for license information.
*--------------------------------------------------------------------------------------------*/

import * as codegen from '@azure-tools/codegen';
import * as rust from '../codemodel/index.js';

const headerText = `// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.

`;

// returns the content preamble common to all emitted files
export function contentPreamble(): string {
  return headerText;
}

// formats doc comments if available
export function formatDocComment(docs?: string): string {
  if (!docs) {
    return '';
  }
  return codegen.comment(docs, '// ', undefined, 120) + '\n';
}

// returns 'pub ' prefix as required
export function emitPub(pub: boolean): string {
  return pub ? 'pub ' : '';
}

// returns the type declaration string for the specified Rust type
export function getTypeDeclaration(type: rust.Type): string {
  switch (type.kind) {
    case 'String':
    case 'bool':
    case 'f32':
    case 'f64':
    case 'i16':
    case 'i32':
    case 'i64':
    case 'i8':
      return type.kind;
    case 'struct':
      return type.name;
  }
}
