// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.

// BEGIN GENERATED CODE -- do not edit from here till END
mod generated;

pub mod clients {
    pub use crate::generated::clients::{
        BytesClient, BytesClientOptions, BytesHeaderClient, BytesPropertyClient, BytesQueryClient,
        BytesRequestBodyClient, BytesResponseBodyClient,
    };
}

pub mod models {
    pub use crate::generated::clients::method_options::{
        BytesHeaderClientBase64Options, BytesHeaderClientBase64UrlArrayOptions,
        BytesHeaderClientBase64UrlOptions, BytesHeaderClientDefaultOptions,
        BytesPropertyClientBase64Options, BytesPropertyClientBase64UrlArrayOptions,
        BytesPropertyClientBase64UrlOptions, BytesPropertyClientDefaultOptions,
        BytesQueryClientBase64Options, BytesQueryClientBase64UrlArrayOptions,
        BytesQueryClientBase64UrlOptions, BytesQueryClientDefaultOptions,
        BytesRequestBodyClientBase64Options, BytesRequestBodyClientBase64UrlOptions,
        BytesRequestBodyClientCustomContentTypeOptions, BytesRequestBodyClientDefaultOptions,
        BytesRequestBodyClientOctetStreamOptions, BytesResponseBodyClientBase64Options,
        BytesResponseBodyClientBase64UrlOptions, BytesResponseBodyClientCustomContentTypeOptions,
        BytesResponseBodyClientDefaultOptions, BytesResponseBodyClientOctetStreamOptions,
    };
    pub use crate::generated::models::*;
}

pub use crate::generated::clients::{BytesClient, BytesClientOptions};
// END GENERATED CODE
