// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//
// Code generated by Microsoft (R) Rust Code Generator.

#![cfg_attr(docsrs, feature(doc_cfg))]

mod generated;
pub use generated::*;
pub mod mixed_subscription_placement;
pub mod two_subscription_resources_method_level;
