// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.

// this should be preserved and is not next to the begin delimiter.

// this should also be preserved right next to the begin delimiter.
// BEGIN GENERATED CODE -- do not edit from here till END
mod generated;

pub mod clients {
    pub use crate::generated::clients::{
        ServiceClient, ServiceClientOptions, ServiceContainerAppendBlobClient,
        ServiceContainerAppendBlobClientOptions, ServiceContainerBlobClient,
        ServiceContainerBlobClientOptions, ServiceContainerBlockBlobClient,
        ServiceContainerBlockBlobClientOptions, ServiceContainerClient,
        ServiceContainerClientOptions, ServiceContainerPageBlobClient,
        ServiceContainerPageBlobClientOptions,
    };
}

pub mod models {
    pub use crate::generated::clients::method_options::{
        ServiceClientFilterBlobsOptions, ServiceClientGetAccountInfoOptions,
        ServiceClientGetPropertiesOptions, ServiceClientGetStatisticsOptions,
        ServiceClientGetUserDelegationKeyOptions, ServiceClientListContainersSegmentOptions,
        ServiceClientSetPropertiesOptions, ServiceClientSubmitBatchOptions,
        ServiceContainerAppendBlobClientAppendBlockFromUrlOptions,
        ServiceContainerAppendBlobClientAppendBlockOptions,
        ServiceContainerAppendBlobClientCreateOptions, ServiceContainerAppendBlobClientSealOptions,
        ServiceContainerBlobClientAbortCopyFromUrlOptions,
        ServiceContainerBlobClientAcquireLeaseOptions, ServiceContainerBlobClientBreakLeaseOptions,
        ServiceContainerBlobClientChangeLeaseOptions, ServiceContainerBlobClientCopyFromUrlOptions,
        ServiceContainerBlobClientCreateSnapshotOptions,
        ServiceContainerBlobClientDeleteImmutabilityPolicyOptions,
        ServiceContainerBlobClientDeleteOptions, ServiceContainerBlobClientDownloadOptions,
        ServiceContainerBlobClientGetAccountInfoOptions,
        ServiceContainerBlobClientGetPropertiesOptions, ServiceContainerBlobClientGetTagsOptions,
        ServiceContainerBlobClientReleaseLeaseOptions, ServiceContainerBlobClientRenewLeaseOptions,
        ServiceContainerBlobClientSetExpiryOptions,
        ServiceContainerBlobClientSetHttpHeadersOptions,
        ServiceContainerBlobClientSetImmutabilityPolicyOptions,
        ServiceContainerBlobClientSetLegalHoldOptions,
        ServiceContainerBlobClientSetMetadataOptions, ServiceContainerBlobClientSetTagsOptions,
        ServiceContainerBlobClientSetTierOptions,
        ServiceContainerBlobClientStartCopyFromUrlOptions,
        ServiceContainerBlobClientUndeleteOptions,
        ServiceContainerBlockBlobClientCommitBlockListOptions,
        ServiceContainerBlockBlobClientGetBlockListOptions,
        ServiceContainerBlockBlobClientPutBlobFromUrlOptions,
        ServiceContainerBlockBlobClientQueryOptions,
        ServiceContainerBlockBlobClientStageBlockFromUrlOptions,
        ServiceContainerBlockBlobClientStageBlockOptions,
        ServiceContainerBlockBlobClientUploadOptions, ServiceContainerClientAcquireLeaseOptions,
        ServiceContainerClientBreakLeaseOptions, ServiceContainerClientChangeLeaseOptions,
        ServiceContainerClientCreateOptions, ServiceContainerClientDeleteOptions,
        ServiceContainerClientFilterBlobsOptions, ServiceContainerClientGetAccessPolicyOptions,
        ServiceContainerClientGetAccountInfoOptions, ServiceContainerClientGetPropertiesOptions,
        ServiceContainerClientListBlobFlatSegmentOptions,
        ServiceContainerClientListBlobHierarchySegmentOptions,
        ServiceContainerClientReleaseLeaseOptions, ServiceContainerClientRenameOptions,
        ServiceContainerClientRenewLeaseOptions, ServiceContainerClientRestoreOptions,
        ServiceContainerClientSetAccessPolicyOptions, ServiceContainerClientSetMetadataOptions,
        ServiceContainerClientSubmitBatchOptions, ServiceContainerPageBlobClientClearPagesOptions,
        ServiceContainerPageBlobClientCopyIncrementalOptions,
        ServiceContainerPageBlobClientCreateOptions,
        ServiceContainerPageBlobClientGetPageRangesDiffOptions,
        ServiceContainerPageBlobClientGetPageRangesOptions,
        ServiceContainerPageBlobClientResizeOptions,
        ServiceContainerPageBlobClientUpdateSequenceNumberOptions,
        ServiceContainerPageBlobClientUploadPagesFromUrlOptions,
        ServiceContainerPageBlobClientUploadPagesOptions,
    };
    pub use crate::generated::enums::*;
    pub use crate::generated::header_traits::*;
    pub use crate::generated::models::*;
}

pub use crate::generated::clients::{
    ServiceClient, ServiceClientOptions, ServiceContainerAppendBlobClient,
    ServiceContainerAppendBlobClientOptions, ServiceContainerBlobClient,
    ServiceContainerBlobClientOptions, ServiceContainerBlockBlobClient,
    ServiceContainerBlockBlobClientOptions, ServiceContainerClient, ServiceContainerClientOptions,
    ServiceContainerPageBlobClient, ServiceContainerPageBlobClientOptions,
};
// END GENERATED CODE
// this should also be preserved right next to the end delimiter.

// this should also be preserved and is not next to the end delimiter.
