// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.

// BEGIN GENERATED CODE -- do not edit from here till END
mod generated;

pub mod clients {
    pub use crate::generated::clients::{NotVersionedClient, NotVersionedClientOptions};
}

pub mod models {
    pub use crate::generated::clients::method_options::{
        NotVersionedClientWithPathApiVersionOptions, NotVersionedClientWithQueryApiVersionOptions,
        NotVersionedClientWithoutApiVersionOptions,
    };
}

pub use crate::generated::clients::{NotVersionedClient, NotVersionedClientOptions};
// END GENERATED CODE
