// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//
// Code generated by Microsoft (R) Rust Code Generator.

#![cfg_attr(docsrs, feature(doc_cfg))]
#![allow(dead_code)]
#![allow(unused_imports)]

mod generated;
pub use generated::*;
