trigger:
  branches:
    include:
      - main
  paths:
    include:
      - packages/typespec-rust/test/spector
pr: none

variables:
  - name: TypeSpecRustPkgDir
    value: $(System.DefaultWorkingDirectory)/packages/typespec-rust

steps:
  - template: /eng/pipelines/templates/steps/set-env.yaml

  - template: /eng/pipelines/templates/steps/build-test.yaml

  - task: AzureCLI@2
    displayName: Upload Spector Test Coverage
    inputs:
      azureSubscription: "Typespec Storage"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: npx tsp-spector upload-coverage --containerName=coverages --generatorName @azure-tools/typespec-rust --storageAccountName typespec --generatorVersion $(node -p -e "require('./package.json').version") --generatorMode azure
      workingDirectory: $(TypeSpecRustPkgDir)
