trigger:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*

jobs:
  - job: "TypeSpec_Rust_CI"
    displayName: "Run TypeSpec Rust CI Checks"

    strategy:
      matrix:
        Linux:
          image: $(LINUXNEXTVMIMAGE)
          pool: $(LINUXPOOL)

    pool:
      name: $(pool)
      image: "$(image)"
      os: linux

    steps:
      - template: ../steps/set-env.yaml

      - template: ../steps/build-test.yaml
