trigger: none
pr: none

parameters:
- name: publish_dev
  displayName: 'Publish Dev Release only'
  type: boolean
  default: true
- name: release_autorestrust
  displayName: '@autorest/rust'
  type: boolean
  default: false

extends: 
  template: /eng/pipelines/templates/stages/1es-redirect.yml
  parameters:
    stages:
    - stage: Release

      variables: 
        - template: /eng/pipelines/templates/variables/image.yml

      jobs:
        - job: Release 
          pool:
            name: $(LINUXPOOL)
            image: $(LINUXVMIMAGE)
            os: linux

          steps:
            - template: /eng/pipelines/templates/steps/set-env.yaml

            - ${{ if eq(parameters.release_autorestrust, true) }}:
              - template: /eng/pipelines/templates/steps/build-test.yaml
              - template: /eng/pipelines/templates/steps/publish-release.yaml
                parameters:
                  PackagePath: "typespec-rust"
                  PackageFileName: "azure-tools-typespec-rust"
                  ReleaseName: "Autorest for Rust v$currentVersion"
                  ReleaseNotes: "Autorest for Rust track 2"
                  PublishDevVersion: ${{ parameters.publish_dev }}
