// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator.

#![cfg_attr(docsrs, feature(doc_auto_cfg))]

// TODO: LRO client has dead code, https://github.com/Azure/typespec-rust/issues/188
#[allow(dead_code)]
mod generated;
pub use generated::*;
