// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.

// BEGIN GENERATED CODE -- do not edit from here till END
mod generated;

pub mod clients {
    pub use crate::generated::clients::*;
}

pub mod models {
    pub use crate::generated::models::*;
}

pub use crate::generated::clients::{
    XmlClient, XmlClientOptions, XmlModelWithArrayOfModelValueClientGetOptions,
    XmlModelWithArrayOfModelValueClientPutOptions, XmlModelWithAttributesValueClientGetOptions,
    XmlModelWithAttributesValueClientPutOptions, XmlModelWithDictionaryValueClientGetOptions,
    XmlModelWithDictionaryValueClientPutOptions, XmlModelWithEmptyArrayValueClientGetOptions,
    XmlModelWithEmptyArrayValueClientPutOptions, XmlModelWithEncodedNamesValueClientGetOptions,
    XmlModelWithEncodedNamesValueClientPutOptions, XmlModelWithOptionalFieldValueClientGetOptions,
    XmlModelWithOptionalFieldValueClientPutOptions, XmlModelWithRenamedArraysValueClientGetOptions,
    XmlModelWithRenamedArraysValueClientPutOptions, XmlModelWithRenamedFieldsValueClientGetOptions,
    XmlModelWithRenamedFieldsValueClientPutOptions, XmlModelWithSimpleArraysValueClientGetOptions,
    XmlModelWithSimpleArraysValueClientPutOptions, XmlModelWithTextValueClientGetOptions,
    XmlModelWithTextValueClientPutOptions, XmlModelWithUnwrappedArrayValueClientGetOptions,
    XmlModelWithUnwrappedArrayValueClientPutOptions, XmlSimpleModelValueClientGetOptions,
    XmlSimpleModelValueClientPutOptions,
};
// END GENERATED CODE
