// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.

// BEGIN GENERATED CODE -- do not edit from here till END
mod generated;

pub mod clients {
    pub use crate::generated::clients::{
        DurationClient, DurationClientOptions, DurationHeaderClient, DurationPropertyClient,
        DurationQueryClient,
    };
}

pub mod models {
    pub use crate::generated::clients::method_options::{
        DurationHeaderClientDefaultOptions, DurationHeaderClientFloat64SecondsOptions,
        DurationHeaderClientFloatSecondsOptions, DurationHeaderClientInt32SecondsOptions,
        DurationHeaderClientIso8601ArrayOptions, DurationHeaderClientIso8601Options,
        DurationPropertyClientDefaultOptions, DurationPropertyClientFloat64SecondsOptions,
        DurationPropertyClientFloatSecondsArrayOptions, DurationPropertyClientFloatSecondsOptions,
        DurationPropertyClientInt32SecondsOptions, DurationPropertyClientIso8601Options,
        DurationQueryClientDefaultOptions, DurationQueryClientFloat64SecondsOptions,
        DurationQueryClientFloatSecondsOptions, DurationQueryClientInt32SecondsArrayOptions,
        DurationQueryClientInt32SecondsOptions, DurationQueryClientIso8601Options,
    };
    pub use crate::generated::models::*;
}

pub use crate::generated::clients::{DurationClient, DurationClientOptions};
// END GENERATED CODE
