// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.

// BEGIN GENERATED CODE -- do not edit from here till END
mod generated;

pub mod clients {
    pub use crate::generated::clients::{OAuth2Client, OAuth2ClientOptions};
}

pub mod models {
    pub use crate::generated::clients::method_options::{
        OAuth2ClientInvalidOptions, OAuth2ClientValidOptions,
    };
}

pub use crate::generated::clients::{OAuth2Client, OAuth2ClientOptions};
// END GENERATED CODE
