// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.

mod generated;

pub mod clients {
    pub use crate::generated::clients::*;
}

pub use crate::generated::clients::{
    OAuth2Client, OAuth2ClientInvalidOptions, OAuth2ClientOptions, OAuth2ClientValidOptions,
};
