// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.

// BEGIN GENERATED CODE -- do not edit from here till END
mod generated;

pub mod clients {
    pub use crate::generated::clients::{
        TwoOperationGroupClient, TwoOperationGroupClientOptions, TwoOperationGroupGroup1Client,
        TwoOperationGroupGroup2Client,
    };
}

pub mod models {
    pub use crate::generated::clients::method_options::{
        TwoOperationGroupGroup1ClientFourOptions, TwoOperationGroupGroup1ClientOneOptions,
        TwoOperationGroupGroup1ClientThreeOptions, TwoOperationGroupGroup2ClientFiveOptions,
        TwoOperationGroupGroup2ClientSixOptions, TwoOperationGroupGroup2ClientTwoOptions,
    };
    pub use crate::generated::enums::*;
}

pub use crate::generated::clients::{TwoOperationGroupClient, TwoOperationGroupClientOptions};
// END GENERATED CODE
