// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.

mod generated;

pub mod clients {
    pub use crate::generated::clients::*;
}

pub mod models {
    pub use crate::generated::models::*;
}

pub use crate::generated::clients::{
    DatetimeClient, DatetimeClientOptions, DatetimeHeaderClientDefaultOptions,
    DatetimeHeaderClientRfc3339Options, DatetimeHeaderClientRfc7231Options,
    DatetimeHeaderClientUnixTimestampArrayOptions, DatetimeHeaderClientUnixTimestampOptions,
    DatetimePropertyClientDefaultOptions, DatetimePropertyClientRfc3339Options,
    DatetimePropertyClientRfc7231Options, DatetimePropertyClientUnixTimestampArrayOptions,
    DatetimePropertyClientUnixTimestampOptions, DatetimeQueryClientDefaultOptions,
    DatetimeQueryClientRfc3339Options, DatetimeQueryClientRfc7231Options,
    DatetimeQueryClientUnixTimestampArrayOptions, DatetimeQueryClientUnixTimestampOptions,
    DatetimeResponseHeaderClientDefaultOptions, DatetimeResponseHeaderClientRfc3339Options,
    DatetimeResponseHeaderClientRfc7231Options, DatetimeResponseHeaderClientUnixTimestampOptions,
};
