---
# configure plugins first
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
plugins:
- "@typescript-eslint"

# then inherit the common settings
extends:
- "../../.default-eslintrc.yaml"
