// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//
// Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.

#![cfg_attr(docsrs, feature(doc_cfg))]
#![allow(clippy::disallowed_names)]
mod generated;
pub use generated::*;
